### ISSUE TITLE
[Competition Bug]: Bitsong Bug report.

### ISSUE THREAD

**Issue by hellowik71** [bitsongofficial/sinfonia-ui#279] opened 2022-05-10 03:39 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

After my Twitter and address are eligible to take part in the testnet competition, I'm having trouble connecting my wallet. 
After i used another laptop and it connected successfully

### Describe the issue behavior

After successfully connecting to testnet, it turned out that my balance in the wallet was not detected, then tried restarting my laptop but still no change. then I let it about 1 hour later detected. 
Tried the swap feature 3× my transaction failed continuously, after I tried it again it worked.
There may be a lot to improve from the bitsong site, for example it is difficult to connect the wallet, the balance is not detected and the swap often fails. 
So far I've only experienced these 3 problems, if I find the latest bug I will definitely report it to you

### BitSong Public Address

bitsong1kmzkwtcdh4fhjz2ddy9gjcz4f3mf00yjv8kz8y

### Osmosis Public Address

osmo1k48lsln8v27q6fks2vdw8qjrmjv8wuut82u6ay

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.40

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment] 2022-05-10 09:58
Can you please add videos or images?

Thank you.

**Comment by Giorgionocera** [comment] 2022-05-10 09:58
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by hellowik71** [comment] 2022-05-10 10:33
I took this picture when I tried to use a cellphone and laptop

Pada tanggal Sel, 10 Mei 2022 16.59, Giorgio Nocera <
***@***.***> menulis:

**Comment by hellowik71** [comment] 2022-05-10 10:35
> Can you please add videos or images?
> 
> Thank you.

I took this picture when I tried to use a cellphone and laptop
![IMG_20220510_172948_306](https://user-images.githubusercontent.com/91696450/167609770-9c8cee21-99b7-495f-9e76-30d7c1d98dc6.jpg)

**Comment by hellowik71** [comment] 2022-05-10 18:48
> Can you please add videos or images?
> 
> Thank you.

Future removing liquidity doesn't work, I hope the team will fix this problem asap

> Can you please add videos or images?
> 
> Thank you.

Future removing liquidity doesn't work, I hope the team will fix this problem asap

**Comment by DavideSegullo** [comment] 2022-05-11 08:52
What do you mean with "Future removing liquidity doesn't work"

**Comment by hellowik71** [comment] 2022-05-11 09:39
> What do you mean with "Future removing liquidity doesn't work"

I wrote wrong, it should be "feature" not "future" and I also misunderstood that if you want to remove liquidity you have to wait for unbonding for 24 hours

**Comment by Giorgionocera** [comment] 2022-05-16 09:36
So it is not a bug? We can close this issue?

**Comment by Giorgionocera** [comment] 2022-05-17 10:51
Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.

**Comment by hellowik71** [comment] 2022-05-17 11:22
> Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.

For a few days I have no more problems, maybe you can close my issue application. 
Thank you, I can't wait for the mainnet to launch

**Closed** 2022-05-18 17:18 UTC
Labels: bug, competition bug report, waiting for comments
