### ISSUE TITLE
Failed swap but still can swap again and balance not reduce

### ISSUE THREAD

**Issue by adebagoes74** [bitsongofficial/sinfonia-ui#218] opened 2022-05-09 19:45 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I swap bitsong to fan token and after that it showing broadcasting i waiting like 1 hour but its not showing finish so i try to swap again and the new transaction is finish but the old transaction is still broadcasting

### Describe the issue behavior

If swap the balance must reduce no matter the transaction fail or not so we now that transaction is still proses, but if showing broadcasting we dont now how many that transaction progess so i hope it will fixed soon

### BitSong Public Address

bitsong1nlqk7u2w87vk39yt0g0deq8eq4gp95p58qzpe5

### Osmosis Public Address

osmo1h9nyze3hkt3zydkkwtfasuzdpe4fk4x9mq52dr

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment] 2022-05-09 21:18
Duplicate of #172

**Closed** 2022-05-09 21:29 UTC
Labels: duplicate, Review, competition bug report
