### ISSUE TITLE
[Competition Bug]:  Auto scroll up after press "Swap Tokens" (which serves to exchange the position of the tokens in the swap section)

### ISSUE THREAD

**Issue by cbsantos90** [bitsongofficial/sinfonia-ui#184] opened 2022-05-09 16:41 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

bug : UI/UX bug
1. Use the google chrome from desktop with normal zoom (100%)
2. Open the swap through this link https://testnet.sinfonia.zone/swap?from=LOBO&to=CLAY
3. click the "Swap Tokens" button and the bug will appear
![bug 2](https://user-images.githubusercontent.com/98073517/167456192-d69a48be-7d32-4f1a-8e1a-27a9bd74a3d5.gif)

### Describe the issue behavior

bug : UI/UX bug
details : i open the website using google chrome desktop with normal zoom display state (zoom 100%). every time I press the "Swap Tokens" button (which functions to exchange token positions), the screen from the website always automatically scrolls up and it's very annoying because it always covers the "Swap Tokens" button (which functions to make swap transactions). It's not really a big deal, but it's still annoying. I hope the developers can change this.
![bug 2](https://user-images.githubusercontent.com/98073517/167457174-fd9bdc65-bb10-4c0d-9546-08e70fbc6ac1.gif)

### BitSong Public Address

bitsong1g0l3hla7jaf8z9agskdejp3kzh60ufxm6852pj

### Osmosis Public Address

osmo1wtcrmmyysjxln7gkgftncy44m0dl4sr009y5tl

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Roovys** [comment] 2022-05-09 17:19
it doesnt happned to me, even i set the zoom to 100%.

im using 24 inch monitor, what about you?

**Comment by cbsantos90** [comment] 2022-05-10 12:45
i'm using laptop, and the zoom was set to 100%. It should happen to anyone with similar device with me. Maybe your minotor is big and the web's size counts quite tiny to your monitor's perspective

**Comment by Giorgionocera** [comment] 2022-05-30 07:46
Thank you for this submission. This behavior is linked to the change of the route. As a consequence, it is not a bug. It is expected behavior. Moreover, it could be considered as an enhancement for the UX of the platform that we can implement to improve the experience.
So, if you want you can create a new issue with the template of improvement. 
In my opinion, this will be closed as invalid. 
Thank you again.

**Closed** 2022-05-30 11:33 UTC
Labels: bug, invalid, competition bug report
