### ISSUE TITLE
[Competition Bug]: UI/UX bug on swap section

### ISSUE THREAD

**Issue by cbsantos90** [bitsongofficial/sinfonia-ui#180] opened 2022-05-09 16:16 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

first bug : UI/UX bug
1. after i transfered all of my Bitsongs to Osmosis Chain, i open the swap section
2. i swapped 1000 Bitsong to Clay
3. then click "Swap Tokens" to switch the position. Here's the bug appears. The amount of the Bitsong and Clay are not the same like before i click the "Swap Tokens" (or before i switch
![bug 1](https://user-images.githubusercontent.com/98073517/167452790-f76ca7d4-fbe9-4c36-bc43-b23cc299b350.gif)
 position)

second bug : UI/UX bug
after the swap transaction notification appeared, press light mode/dark mode button, the fonts inside the notification box will become transparent
![bug 1+](https://user-images.githubusercontent.com/98073517/167463979-05370b92-860b-4440-9a60-1afa7cdbdd20.gif)

### Describe the issue behavior

first bug : UI/UX
It happened in the swap section.The amount of the Bitsong and Clay are not the same like before i click the "Swap Tokens" (or before i switch position). you can see my gif that i attached. and this bug happens everytime i click the "Swap Tokens"
![bug 1](https://user-images.githubusercontent.com/98073517/167452935-1ece5ee6-7972-4ca7-97db-3421e5cd0e1f.gif)

second bug : UI/UX bug
the fonts inside the transaction notification box becomes transparent when i press the dark/light mode
![bug 1+](https://user-images.githubusercontent.com/98073517/167463928-1020dd9f-2ae8-40a2-bfea-3af0424f3946.gif)

### BitSong Public Address

bitsong1g0l3hla7jaf8z9agskdejp3kzh60ufxm6852pj

### Osmosis Public Address

osmo1wtcrmmyysjxln7gkgftncy44m0dl4sr009y5tl

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

101.0.4951.54

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by cbsantos90** [comment] 2022-05-09 16:20
*it happened for all pairs

**Comment by Giorgionocera** [comment] 2022-07-29 16:09
The first one is not a bug. The second is a duplicate of #192

**Closed by Giorgionocera** 2022-07-29 16:09 UTC
Labels: bug, competition bug report

**Comment by cbsantos90** [comment] 2022-07-29 17:23
i didn't duplicate!!!

**Comment by cbsantos90** [comment] 2022-07-29 17:25
it doesn't make sense

**Comment by cbsantos90** [comment] 2022-07-29 17:28
i submitted the bug earlier

**Comment by cbsantos90** [comment] 2022-07-30 00:22
1 month of waiting, responded by the unprofessionalism behaviour. shame on you @Giorgionocera

**Comment by DavideSegullo** [comment] 2022-07-30 11:41
@cbsantos90 It's a duplicated, you edited your post on 9 May 19:24 CEST, and the issue #192 has been created on 9 May 19:10 CEST

**Comment by Giorgionocera** [comment] 2022-08-02 11:10
> 1 month of waiting, responded by the unprofessional behaviour. shame on you @Giorgionocera

Please, I'm here to listen to your problems. As already reported by @DavideSegullo, 

> you edited your post on 9 May 19:24 CEST, and the issue https://github.com/bitsongofficial/sinfonia-ui/issues/192 has been created on 9 May 19:10 CEST.

What about this statement?

**Comment by cbsantos90** [comment] 2022-08-02 18:40
do you think i copied someone's work?? ofc not! i didn't even know about #192 post. all of ya don't respect my works and my enthusiasm to this project!

**Comment by Giorgionocera** [comment] 2022-08-03 08:17
As you can read from the comment, I said it is a duplicate. I did not say you copied. 
It is a matter of fact that your issue duplicates #192. In this sense, the report you produced is indicating the issue of something already highlighted.

**Comment by cbsantos90** [comment] 2022-08-04 07:15
the difference is only 14 minutes and you don't give some rewards for me who has spent time for this project! also you don't give rewards for the other users who has spent their time to this project! disrespectful! you said that the start prize of the bug bounty is $500 in BTSG, and also that's a lie! once again, very disrespectful!

**Comment by Giorgionocera** [comment] 2022-08-04 08:19
As you might be able to see, the reports had to **be evaluated by an internal commission** and **get approved** in order to be eligible for a prize. However, the report you submitted does not meet any requirements since:

1. It’s been submitted after “someone else” reported the same issue.
2. The report hasn’t been considered a valid one by the commission since it was just a UI error, however, a consolation prize of 1500 BTSG has been assigned to the 1st submitter.
3. We cannot give a consolation prize to 2 different submitters for the same report, which was not even approved by the commission.

In the event, you are able to find and fix any major or critical bug chain side and not only UI error, please feel free to contact us and we'll be glad to evaluate it. 

Best regards.
