### ISSUE TITLE
[Competition Bug]: Transfer amount value becomes -0.025

### ISSUE THREAD

**Issue by cbsantos90** [bitsongofficial/sinfonia-ui#199] opened 2022-05-09 18:00 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

bug : UI/UX bug on "crosschain transfer" in "asset" section
1. open https://testnet.sinfonia.zone/assets
2. press the "up and down" symbol (symbol meaning on transfer) on any token
3. make the chain pair to be Bitsong Testnet --> Osmosis testnet (make sure the number of tokens in the currently reviewed bitsong testnet chain is empty)
4. then press "max" button on the right side. now you'll see the value of the transfer amount is -0.025
![bug 4](https://user-images.githubusercontent.com/98073517/167468547-343b94f6-5112-43e3-b245-3f566bf478e0.gif)

### Describe the issue behavior

bug : UI/UX bug on "crosschain transfer" in "asset" section
the transfer value after I hit the max button became weird (aka -0.025). it happened when the FONTI token on my Bitsong Testnet Chain was empty. I thought it would only happen to this token, but it turns out that the same thing happened to all types of empty tokens on the BitSong Testnet Chain network. but this is not the case for the empty tokens on the Osmosis Testnet network.
![bug 4](https://user-images.githubusercontent.com/98073517/167469679-6211d2fb-0242-47b0-9460-d973be7373fe.gif)

### BitSong Public Address

bitsong1g0l3hla7jaf8z9agskdejp3kzh60ufxm6852pj

### Osmosis Public Address

osmo1wtcrmmyysjxln7gkgftncy44m0dl4sr009y5tl

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment] 2022-05-30 07:57
Thank you for your issue. This is an improvement for the UX of the platform. 
It is not a bug, in fact, if you try to proceed with the transfer you will get an error.
So, if you want you can create a new issue with the template of improvement.
In my opinion, this will be closed as invalid.
Thank you again.

**Closed** 2022-05-30 12:06 UTC
Labels: bug, invalid, competition bug report
