### ISSUE TITLE
[Competition Bug]: UI problem (bug) and suggest

### ISSUE THREAD

**Issue by D3lm4nnn** [bitsongofficial/sinfonia-ui#216] opened 2022-05-09 19:40 UTC
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

-in swap section when i do swap always get broadcasting in history swap and actually my swap is fail then my question is why in history alwasy say broadcasting why not result/report failed so i can do swap again or refresh the web    

 
![image](https://user-images.githubusercontent.com/54407192/167483432-1cad2558-7492-4f4f-ae8c-a529e14689f7.png)

### Describe the issue behavior

for u all after u got broadcasting like me use hard refresh alt+f4 

### BitSong Public Address

bitsong1l4f73jwh4smnz454lprszaa8d4kqs2l2tkhhpz

### Osmosis Public Address

osmo1cj0vvqk60u3l2kp7l2qtptg90ggacqzvkz5y2t

### Which browser are you using?

Google Chrome

### Which is your browser version?

ersion 100.0.4896.127 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment] 2022-05-09 21:11
Duplicate of #172

**Closed** 2022-05-09 21:29 UTC
Labels: duplicate, Review, competition bug report
